name: Build Win64

on: 
    push:
      branches: 
       - master
        

jobs:
  build_win64:
    name: Build Win64
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Install perl
        run: |
          choco install strawberryperl
      - run: mkdir ${{ github.workspace }}/deps/build
      - run: mkdir ${{ github.workspace }}/deps/build/PrusaSlicer_dep
      - name: download deps
        shell: powershell
        run: '(new-object System.Net.WebClient).DownloadFile("https://github.com/SoftFever/FileSharing/releases/download/2/BambuStudio_dep_21Jan2023.zip", "$env:temp\BambuStudio_dep_21Jan2023.zip")'
      - name: extract deps
        working-directory: ${{ github.workspace }}/deps/build
        shell: cmd
        run: '"C:/Program Files/7-Zip/7z.exe" x %temp%\BambuStudio_dep_21Jan2023.zip'

      - run: dir "${{ github.workspace }}\deps\build\PrusaSlicer_dep"
      
      # - name: build deps
      #   id: cache_deps
      #   uses: actions/cache@v3
      #   env:
      #     cache-name: ${{ runner.os }}-cache-PrusaSlicer_deps
      #   with:
      #     path: ${{ github.workspace }}/deps/build/PrusaSlicer_dep
      #     key: ${{ runner.os }}-build-${{ env.cache-name }}

      # - if: ${{ steps.cache_deps.outputs.cache-hit != 'true' }}
      #   name: build deps
      #   working-directory: ${{ github.workspace }}
      #   continue-on-error: true
      #   run: .\build_release.bat deps
   
      # - run:  Get-ChildItem ${{ github.workspace }}/deps/build/ -Exclude PrusaSlicer_dep | Remove-Item -Recurse -Force

      - name: Build studio
        working-directory: ${{ github.workspace }}
        run: .\build_release.bat studio

      # - name: pack app
      #   working-directory: ${{ github.workspace }}/build
      #   shell: cmd
      #   run: '"C:/Program Files/7-Zip/7z.exe" a -tzip BambuStudio-SoftFever_dev_build.zip ${{ github.workspace }}/build/Pleccer'

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Pleccer_Win64_nightly
          path: ${{ github.workspace }}/build/Pleccer
