name: C/C++ Release candidate arm macos

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'master'
    - name: build deps & slicer
      run: ./BuildMacOS.sh -ia
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: rc_arm_macos.tar
        path: build/PrusaSlicer.tar
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: rc_macos.dmg
        path: build/PrusaSlicer.dmg
